CREATE TABLE students AS
   SELECT "11/17/2021 10:52:40" AS time, 3 AS number, "black" AS color, "the number 7 below." AS seven, "Smells Like Teen Spirit" as song, "10/31" as date, "dog" as pet, "2" AS instructor, 1 AS smallest UNION
   SELECT "11/17/2021 10:55:28"        , 28          , "blue"                     , "7"                                     , "Clair De Lune"            , "8/20" , "dog"                                     , "2"      , 4                     UNION
   SELECT "11/17/2021 11:06:35"        , 99          , "white"                    , "seven"                                 , "Smells like Teen Spirit"  , "6/5"  , "cheetah"                                 , "3"      , 1                     UNION
   SELECT "11/17/2021 11:09:04"        , 42          , "green"                    , "7"                                     , "Shelter"                  , "9/16" , "capybara"                                , "4"      , 1                     UNION
   SELECT "11/17/2021 11:12:56"        , 8           , "purple"                   , "7"                                     , "Old Town Road"            , "5/15" , "squirrell"                               , "4"      , 26                    UNION
   SELECT "11/17/2021 11:19:53"        , 23          , "gern"                     , "seven"                                 , "Dancing Queen"            , "7/23" , "megladon"                                , "1"      , 1                     UNION
   SELECT "11/17/2021 11:27:34"        , 88          , "red"                     , "You're not the boss of me!"            , "Dancing Queen"            , "7/11" , "deer"                                   , "1"      , 1                     UNION
   SELECT "11/17/2021 11:31:44"        , 23          , "purple"                   , "the number 7 below."                   , "Old Town Road"            , "5/23" , "porcupine"                               , "3"      , 48                    UNION
   SELECT "11/17/2021 11:55:11"        , 12          , "white"                    , "You're not the boss of me!"            , "Shake It Off"             , "5/3"  , "cat"                                     , "5"      , 44                    UNION
   SELECT "11/17/2021 11:57:34"        , 16          , "black"                    , "7"                                     , "STAY"                     , "1/1"  , "snake"                                   , "5"      , 19                    UNION
   SELECT "11/17/2021 11:59:48"        , 27          , "pink"                     , "7"                                     , "Dancing Queen"            , "8/13" , "dolphin"                                 , "4"      , 37                    UNION
   SELECT "11/17/2021 12:04:38"        , 5           , "orange"                   , "7"                                     , "Clair De Lune"            , "10/18", "tiger"                                   , "4"      , 412                   UNION
   SELECT "11/17/2021 12:14:37"        , 99          , "forest green"             , "7"                                     , "STAY"                     , "12/31", "cat"                                     , "1"      , 13                    UNION
   SELECT "11/17/2021 12:16:43"        , 38          , "blue"                     , "the number 7 below."                   , "All I want for Christmas" , "11/11", "elephant"                                , "1"      , 28                    UNION
   SELECT "11/17/2021 12:19:45"        , 88          , "turquoise"                , "Choose this option instead"            , "STAY"                     , "4/16" , "dragon"                                  , "2"      , 17                    UNION
   SELECT "11/17/2021 12:23:14"        , 7           , "green"                    , "You're not the boss of me!"            , "Shelter"                  , "4/6"  , "cat"                                     , "1"      , 234                   UNION
   SELECT "11/17/2021 12:26:03"        , 69          , "ocean blue"               , "You're not the boss of me!"            , "Shelter"                  , "11/19", "schnauzer dog"                           , "5"      , 57                    UNION
   SELECT "11/17/2021 12:30:12"        , 9           , "deep blue"                , "7"                                     , "Shake It Off"             , "1/3"  , "horse"                                   , "2"      , 37                    UNION
   SELECT "11/17/2021 12:32:54"        , 42          , "pink"                     , "the number 7 below."                   , "Shelter"                  , "10/27", "cat"                                     , "2"      , 16                    UNION
   SELECT "11/17/2021 12:35:33"        , 13          , "green"                    , "Choose this option instead"            , "Smells like Teen Spirit"  , "7/12" , "penguin"                                 , "4"      , 7                     UNION
   SELECT "11/17/2021 12:48:31"        , 17          , "green"                    , "the number 7 below."                   , "Clair De Lune"            , "7/13" , "dog"                                     , "1"      , 38                    UNION
   SELECT "11/17/2021 12:51:43"        , 21          , "green"                    , "7"                                     , "Everytime We Touch"       , "9/2"  , "owl monkey"                              , "1"      , 59                    UNION
   SELECT "11/17/2021 12:51:50"        , 28          , "purple"                   , "seven"                                 , "Dancing Queen"            , "1/1"  , "tiger"                                   , "4"      , 1                     UNION
   SELECT "11/17/2021 12:59:11"        , 69          , "red"                      , "7"                                     , "STAY"                     , "1/1"  , "tiger"                                   , "5"      , 1                     UNION
   SELECT "11/17/2021 13:04:12"        , 3.1415962   , "yellow"                   , "seven"                                 , "Smells like Teen Spirit"  , "1/1"  , "penguin !"                               , "1"      , 13                    UNION
   SELECT "11/17/2021 13:04:27"        , 72          , "black"                    , "7"                                     , "Dancing Queen"            , "12/25", "bear"                                    , "5"      , 34                    UNION
   SELECT "11/17/2021 13:05:09"        , 7           , "purple"                   , "7"                                     , "Everytime We Touch"       , "12/27", "tucan"                                   , "2"      , 57                    UNION
   SELECT "11/17/2021 13:05:14"        , 17          , "blue"                     , "7"                                     , "All I want for Christmas" , "8/30" , "cat"                                     , "1"      , 12                    UNION
   SELECT "11/17/2021 13:07:02"        , 6           , "black"                    , "the number 7 below."                   , "Clair De Lune"            , "11/11", "owl"                                     , "5"      , 90                    UNION
   SELECT "11/17/2021 13:13:55"        , 2           , "blue"                     , "7"                                     , "Shake It Off"             , "5/8"  , "dog"                                     , "4"      , 47                    UNION
   SELECT "11/17/2021 13:16:48"        , 2           , "blue"                     , "Choose this option instead"            , "Clair De Lune"            , "12/26", "whale"                                   , "5"      , 2                     UNION
   SELECT "11/17/2021 13:17:11"        , 4           , "muted blue"               , "7"                                     , "Clair De Lune"            , "11/28", "giraffe"                                 , "2"      , 24                    UNION
   SELECT "11/17/2021 13:17:33"        , 3           , "blue"                     , "the number 7 below."                   , "Old Town Road"            , "3/15" , "dog"                                     , "3"      , 1                     UNION
   SELECT "11/17/2021 13:20:14"        , 69          , "blue"                     , "the number 7 below."                   , "Smells like Teen Spirit"  , "3/11" , "crocodile"                               , "4"      , 14                    UNION
   SELECT "11/17/2021 13:24:58"        , 9           , "red"                      , "7"                                     , "Old Town Road"            , "6/6"  , "kitten"                                  , "2"      , 1                     UNION
   SELECT "11/17/2021 13:31:16"        , 64          , "green"                   , "the number 7 below."                   , "Clair De Lune"            , "4/6"  , "a dog"                                   , "5"      , 96024                 UNION
   SELECT "11/17/2021 13:32:00"        , 7           , "blue"                     , "seven"                                 , "Shake It Off"             , "3/25" , "penguin"                                 , "4"      , 13                    UNION
   SELECT "11/17/2021 13:32:19"        , 23          , "green"                    , "Choose this option instead"            , "Dancing Queen"            , "7/4"  , "fox"                                     , "1"      , 213                   UNION
   SELECT "11/17/2021 13:37:55"        , 72          , "green"                    , "7"                                     , "All I want for Christmas" , "3/21" , "panda"                                   , "2"      , 1                     UNION
   SELECT "11/17/2021 13:41:39"        , 72          , "mint"                     , "7"                                     , "All I want for Christmas" , "11/11", "ostrich"                                 , "3"      , 34                    UNION
   SELECT "11/17/2021 13:43:16"        , 12          , "blue"                     , "7"                                     , "All I want for Christmas" , "11/5" , "giraffe"                                 , "2"      , 1                     UNION
   SELECT "11/17/2021 13:46:51"        , 55          , "purple"                   , "7"                                     , "Clair De Lune"            , "3/12" , "dog"                                     , "5"      , 31                    UNION
   SELECT "11/17/2021 13:52:09"        , 4           , "green"                    , "7"                                     , "Shake It Off"             , "10/11", "horse"                                   , "1"      , 21                    UNION
   SELECT "11/17/2021 13:54:58"        , 16          , "blue"                     , "the number 7 below."                   , "STAY"                     , "12/22", "fish"                                    , "1"      , 1                     UNION
   SELECT "11/17/2021 13:57:26"        , 21          , "yellow"                   , "Choose this option instead"            , "Everytime We Touch"       , "9/17" , "crab"                                    , "4"      , 31                    UNION
   SELECT "11/17/2021 13:57:37"        , 28          , "blue"                     , "7"                                     , "Turntables"               , "1/1"  , "cat"                                     , "2"      , 1                     UNION
   SELECT "11/17/2021 14:01:02"        , 25          , "cyan"                     , "7"                                     , "Everytime We Touch"       , "2/13" , "leopard"                                 , "4"      , 111                   UNION
   SELECT "11/17/2021 14:02:57"        , 3.14159265  , "cookie"                   , "You're not the boss of me!"            , "Dancing Queen"            , "6/9"  , "john denero"                             , "2"      , 8                     UNION
   SELECT "11/17/2021 14:05:14"        , 7           , "green"                    , "7"                                     , "Old Town Road"            , "2/10" , "cheetah"                                 , "4"      , 1                     UNION
   SELECT "11/17/2021 14:05:22"        , 2           , "red"                      , "You're not the boss of me!"            , "Dancing Queen"            , "5/15" , "dog - pitbull"                           , "1"      , 99                    UNION
   SELECT "11/17/2021 14:05:41"        , 79          , "orange"                   , "7"                                     , "Clair De Lune"            , "12/25", "none"                                    , "3"      , 91                    UNION
   SELECT "11/17/2021 14:05:48"        , 44          , "black"                    , "the number 7 below."                   , "Dancing Queen"            , "3/26" , "dragon"                                  , "3"      , 1                     UNION
   SELECT "11/17/2021 14:05:52"        , 47          , "#ccff00"                  , "the number 7 below."                   , "Shake It Off"             , "11/11", "cat"                                     , "2"      , 1153                  UNION
   SELECT "11/17/2021 14:05:53"        , 5           , "black"                   , "7"                                     , "Dancing Queen"            , "10/21", "dog"                                    , "1"      , 1                     UNION
   SELECT "11/17/2021 14:06:02"        , 7           , "blue"                     , "7"                                     , "Clair De Lune"            , "6/15" , "elephant"                                , "1"      , 1                     UNION
   SELECT "11/17/2021 14:06:05"        , 8           , "green"                    , "7"                                     , "Everytime We Touch"       , "6/27" , "panda"                                   , "5"      , 1                     UNION
   SELECT "11/17/2021 14:06:09"        , 13          , "black"                    , "the number 7 below."                   , "Everytime We Touch"       , "10/12", "wolf"                                    , "4"      , 995                   UNION
   SELECT "11/17/2021 14:06:21"        , 8           , "blue"                     , "7"                                     , "Dancing Queen"            , "1/14" , "platypus"                                , "4"      , 23                    UNION
   SELECT "11/17/2021 14:06:28"        , 2           , "don't have one"           , "7"                                     , "All I want for Christmas" , "11/17", "cat"                                     , "2"      , 1                     UNION
   SELECT "11/17/2021 14:06:30"        , 16          , "green"                    , "7"                                     , "Clair De Lune"            , "3/6"  , "raven"                                   , "4"      , 1                     UNION
   SELECT "11/17/2021 14:06:34"        , 18          , "red"                      , "7"                                     , "Dancing Queen"            , "4/5"  , "dog"                                     , "4"      , 2                     UNION
   SELECT "11/17/2021 14:06:34"        , 13          , "green"                    , "the number 7 below."                   , "STAY"                     , "5/31" , "dog"                                     , "4"      , 1                     UNION
   SELECT "11/17/2021 14:06:37"        , 99          , "yellow"                   , "the number 7 below."                   , "All I want for Christmas" , "10/23", "unicorn"                                 , "2"      , 2                     UNION
   SELECT "11/17/2021 14:06:38"        , 23          , "cyan"                     , "the number 7 below."                   , "All I want for Christmas" , "12/25", "pterodactyl"                             , "1"      , 67                    UNION
   SELECT "11/17/2021 14:06:57"        , 20          , "red"                      , "the number 7 below."                   , "Smells like Teen Spirit"  , "12/17", "a sloth"                                 , "1"      , 2                     UNION
   SELECT "11/17/2021 14:07:31"        , 77          , "black"                    , "7"                                     , "Clair De Lune"            , "2/17" , "bear"                                    , "5"      , 8                     UNION
   SELECT "11/17/2021 14:07:34"        , 69          , "blue"                     , "the number 7 below."                   , "Shelter"                  , "4/20" , "fox"                                     , "1"      , 1                     UNION
   SELECT "11/17/2021 14:07:55"        , 28          , "midnight green"           , "the number 7 below."                   , "Everytime We Touch"       , "4/1"  , "artic fox or sea otter"                  , "5"      , 9                     UNION
   SELECT "11/17/2021 14:08:06"        , 3.1415      , "burgundy"                 , "the number 7 below."                   , "Clair De Lune"            , "6/28" , "axolotl"                                 , "2"      , 8                     UNION
   SELECT "11/17/2021 14:08:17"        , 79          , "purple"                   , "the number 7 below."                   , "Shake It Off"             , "4/13" , "doggy"                                   , "1"      , 5                     UNION
   SELECT "11/17/2021 14:08:22"        , 11          , "purple-blue"              , "Choose this option instead"            , "Clair De Lune"            , "12/29", "penguin"                                 , "2"      , 69                    UNION
   SELECT "11/17/2021 14:09:06"        , 7           , "green"                    , "7"                                     , "STAY"                     , "9/13" , "dragon"                                  , "5"      , 1                     UNION
   SELECT "11/17/2021 14:09:26"        , 21          , "white"                    , "7"                                     , "Shelter"                  , "7/28" , "koala"                                   , "4"      , 1                     UNION
   SELECT "11/17/2021 14:09:39"        , 25          , "blue"                     , "the number 7 below."                   , "Clair De Lune"            , "9/1"  , "lion"                                    , "5"      , 1                     UNION
   SELECT "11/17/2021 14:09:43"        , 70          , "green"                    , "seven"                                 , "Dancing Queen"            , "4/29" , "peacock"                                 , "4"      , 3                     UNION
   SELECT "11/17/2021 14:09:53"        , 88          , "sky blue"                 , "the number 7 below."                   , "STAY"                     , "7/1"  , "hamster"                                 , "5"      , 11                    UNION
   SELECT "11/17/2021 14:09:53"        , 30          , "lavender"                 , "7"                                     , "Shake It Off"             , "10/30", "koala"                                   , "4"      , 13                    UNION
   SELECT "11/17/2021 14:09:55"        , 69          , "red"                      , "7"                                     , "Old Town Road"            , "7/22" , "human"                                   , "4"      , 9                     UNION
   SELECT "11/17/2021 14:09:59"        , 24          , "orange"                   , "You're not the boss of me!"            , "Shelter"                  , "8/24" , "corgi + golden retriever mix doggy"      , "5"      , 1                     UNION
   SELECT "11/17/2021 14:10:07"        , 7           , "purple"                   , "7"                                     , "Shake It Off"             , "5/7"  , "cockapoo"                                , "1"      , 1                     UNION
   SELECT "11/17/2021 14:10:08"        , 69          , "blue"                    , "You're not the boss of me!"            , "Old Town Road"            , "4/20" , "panda"                                   , "4"      , 1                     UNION
   SELECT "11/17/2021 14:10:09"        , 9           , "purple"                   , "Choose this option instead"            , "Dancing Queen"            , "12/16", "snow leopard"                            , "5"      , 11                    UNION
   SELECT "11/17/2021 14:10:12"        , 21          , "red"                      , "7"                                     , "STAY"                     , "11/17", "hedgehog"                                , "5"      , 1                     UNION
   SELECT "11/17/2021 14:10:14"        , 7           , "blue"                     , "7"                                     , "STAY"                     , "2/21" , "tiger"                                   , "2"      , 1                     UNION
   SELECT "11/17/2021 14:10:24"        , 26          , "green"                    , "Choose this option instead"            , "Clair De Lune"            , "10/8" , "i can't take care of pets when i can't even take care of myself", "1"      , 19                    UNION
   SELECT "11/17/2021 14:10:25"        , 7           , "electric blue"            , "Choose this option instead"            , "Old Town Road"            , "6/12" , "quokka"                                  , "1"      , 1                     UNION
   SELECT "11/17/2021 14:10:30"        , 42          , "burgundy"                 , "Choose this option instead"            , "Everytime We Touch"       , "1/1"  , "platypus"                                , "3"      , 1                     UNION
   SELECT "11/17/2021 14:10:31"        , 27          , "blue"                     , "You're not the boss of me!"            , "STAY"                     , "9/27" , "squirrel monkey"                         , "2"      , 1                     UNION
   SELECT "11/17/2021 14:10:32"        , 8           , "red"                      , "the number 7 below."                   , "STAY"                     , "1/1"  , "golden retriever"                        , "4"      , 1                     UNION
   SELECT "11/17/2021 14:10:32"        , 5           , "red"                      , "7"                                     , "Dancing Queen"            , "7/1"  , "penguin"                                 , "2"      , 1                     UNION
   SELECT "11/17/2021 14:10:34"        , 10          , "blue"                     , "the number 7 below."                   , "Shelter"                  , "6/21" , "cat"                                     , "3"      , 43                    UNION
   SELECT "11/17/2021 14:10:47"        , 9           , "turquoise"                , "the number 7 below."                   , "Everytime We Touch"       , "9/11" , "phoenix"                                 , "1"      , 1                     UNION
   SELECT "11/17/2021 14:10:47"        , 17          , "blue"                     , "the number 7 below."                   , "Dancing Queen"            , "3/14" , "dog"                                     , "2"      , 1                     UNION
   SELECT "11/17/2021 14:10:49"        , 3           , "blue"                     , "7"                                     , "Smells like Teen Spirit"  , "1/4"  , "labrador retriever"                      , "3"      , 1                     UNION
   SELECT "11/17/2021 14:10:58"        , 42          , "azure"                    , "Choose this option instead"            , "Smells like Teen Spirit"  , "3/12" , "an intelligent axolotl"                  , "2"      , 827                   UNION
   SELECT "11/17/2021 14:11:07"        , 11          , "purple"                   , "7"                                     , "STAY"                     , "4/20" , "panda"                                   , "3"      , 1                     UNION
   SELECT "11/17/2021 14:11:08"        , 12          , "silver"                   , "seven"                                 , "Shake It Off"             , "2/2"  , "red panda"                               , "2"      , 71                    UNION
   SELECT "11/17/2021 14:11:09"        , 4           , "black"                    , "Choose this option instead"            , "Down With The Sickness"   , "11/11", "bunny"                                   , "5"      , 1                     UNION
   SELECT "11/17/2021 14:11:12"        , 4           , "green"                    , "the number 7 below."                   , "STAY"                     , "4/4"  , "panda"                                   , "4"      , 23                    UNION
   SELECT "11/17/2021 14:11:23"        , 33          , "red"                      , "the number 7 below."                   , "All I want for Christmas" , "2/13" , "husky"                                   , "2"      , 1;

CREATE TABLE numbers AS
   SELECT "11/17/2021 10:52:40" AS time, "True" AS "0", "True" AS "1", "True" AS "2", "True" AS "3", "True" AS "4", "True" AS "5", "True" AS "6", "True" AS "7", "True" AS "8", "True" AS "9", "False" AS "10", "True" AS "2021", "True" AS "2022", "True" AS "9000", "False" AS "9001" UNION
   SELECT "11/17/2021 10:55:28"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 11:06:35"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "True" , "True" , "True" , "False" UNION
   SELECT "11/17/2021 11:09:04"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 11:12:56"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True"  UNION
   SELECT "11/17/2021 11:19:53"        , "False", "False", "False", "True" , "False", "False", "True" , "False", "True" , "False", "True" , "False", "True" , "True" , "True"  UNION
   SELECT "11/17/2021 11:27:34"        , "False", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "False", "False", "True" , "False", "True" , "False" UNION
   SELECT "11/17/2021 11:31:44"        , "False", "True" , "False", "True" , "True" , "False", "True" , "False", "True" , "True" , "False", "True" , "False", "True" , "True"  UNION
   SELECT "11/17/2021 11:55:11"        , "True" , "True" , "True" , "False", "True" , "False", "True" , "True" , "False", "False", "False", "True" , "False", "False", "False" UNION
   SELECT "11/17/2021 11:57:34"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 11:59:48"        , "False", "True" , "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 12:04:38"        , "False", "True" , "True" , "False", "True" , "False", "True" , "True" , "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 12:14:37"        , "False", "True" , "False", "False", "False", "True" , "False", "False", "True" , "False", "True" , "True" , "True" , "False", "True"  UNION
   SELECT "11/17/2021 12:16:43"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 12:19:45"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 12:23:14"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False" UNION
   SELECT "11/17/2021 12:26:03"        , "True" , "True" , "True" , "True" , "False", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 12:30:12"        , "True" , "True" , "False", "False", "False", "False", "False", "True" , "True" , "True" , "False", "False", "True" , "True" , "True"  UNION
   SELECT "11/17/2021 12:32:54"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "True" , "True" , "True" , "True" , "True" , "False", "True"  UNION
   SELECT "11/17/2021 12:35:33"        , "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "False", "True" , "True" , "True" , "False", "False" UNION
   SELECT "11/17/2021 12:48:31"        , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "True" , "False" UNION
   SELECT "11/17/2021 12:51:43"        , "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "11/17/2021 12:51:50"        , "True" , "False", "False", "False", "True" , "False", "False", "True" , "True" , "False", "False", "False", "True" , "False", "True"  UNION
   SELECT "11/17/2021 12:59:11"        , "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 13:04:12"        , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 13:04:27"        , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False", "False" UNION
   SELECT "11/17/2021 13:05:09"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 13:05:14"        , "True" , "False", "False", "True" , "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 13:07:02"        , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 13:13:55"        , "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "11/17/2021 13:16:48"        , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 13:17:11"        , "True" , "False", "True" , "True" , "True" , "True" , "False", "False", "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "11/17/2021 13:17:33"        , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 13:20:14"        , "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "True" , "False", "True" , "False", "False", "False" UNION
   SELECT "11/17/2021 13:24:58"        , "True" , "True" , "True" , "False", "True" , "False", "True" , "True" , "False", "True" , "True" , "False", "False", "False", "False" UNION
   SELECT "11/17/2021 13:31:16"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 13:32:00"        , "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "True" , "False", "True" , "True" , "False", "True"  UNION
   SELECT "11/17/2021 13:32:19"        , "True" , "True" , "False", "True" , "False", "False", "True" , "False", "True" , "False", "False", "True" , "False", "True" , "False" UNION
   SELECT "11/17/2021 13:37:55"        , "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "11/17/2021 13:41:39"        , "False", "False", "False", "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 13:43:16"        , "False", "True" , "True" , "True" , "True" , "False", "True" , "False", "True" , "True" , "True" , "True" , "False", "True" , "False" UNION
   SELECT "11/17/2021 13:46:51"        , "False", "True" , "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "True" , "False", "False", "False" UNION
   SELECT "11/17/2021 13:52:09"        , "True" , "True" , "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "True" , "False", "False", "True"  UNION
   SELECT "11/17/2021 13:54:58"        , "False", "True" , "True" , "False", "False", "False", "True" , "True" , "False", "False", "True" , "True" , "False", "True" , "False" UNION
   SELECT "11/17/2021 13:57:26"        , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 13:57:37"        , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:01:02"        , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True" , "False" UNION
   SELECT "11/17/2021 14:02:57"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 14:05:14"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 14:05:22"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 14:05:41"        , "True" , "True" , "True" , "True" , "True" , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:05:48"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 14:05:52"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 14:05:53"        , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:06:02"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 14:06:05"        , "False", "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:06:09"        , "False", "False", "False", "False", "True" , "False", "True" , "True" , "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:06:21"        , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:06:28"        , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 14:06:30"        , "True" , "False", "True" , "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "False" UNION
   SELECT "11/17/2021 14:06:34"        , "True" , "False", "False", "True" , "True" , "True" , "True" , "False", "False", "False", "False", "True" , "False", "True" , "False" UNION
   SELECT "11/17/2021 14:06:34"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 14:06:37"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 14:06:38"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "True"  UNION
   SELECT "11/17/2021 14:06:57"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 14:07:31"        , "True" , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:07:34"        , "False", "False", "True" , "False", "True" , "False", "False", "False", "False", "True" , "False", "True" , "False", "False", "False" UNION
   SELECT "11/17/2021 14:07:55"        , "True" , "True" , "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "True" , "True" , "False", "False" UNION
   SELECT "11/17/2021 14:08:06"        , "True" , "True" , "True" , "True" , "False", "False", "False", "True" , "False", "True" , "True" , "False", "True" , "False", "True"  UNION
   SELECT "11/17/2021 14:08:17"        , "False", "True" , "True" , "True" , "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "True"  UNION
   SELECT "11/17/2021 14:08:22"        , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "True"  UNION
   SELECT "11/17/2021 14:09:06"        , "False", "True" , "False", "False", "True" , "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "True"  UNION
   SELECT "11/17/2021 14:09:26"        , "True" , "True" , "True" , "True" , "False", "True" , "False", "False", "False", "True" , "False", "True" , "False", "False", "False" UNION
   SELECT "11/17/2021 14:09:39"        , "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:09:43"        , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:09:53"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 14:09:53"        , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:09:55"        , "False", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "True" , "True" , "True"  UNION
   SELECT "11/17/2021 14:09:59"        , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:10:07"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:10:08"        , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 14:10:09"        , "True" , "True" , "True" , "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "True"  UNION
   SELECT "11/17/2021 14:10:12"        , "True" , "True" , "False", "False", "True" , "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False" UNION
   SELECT "11/17/2021 14:10:14"        , "True" , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "False", "False", "True"  UNION
   SELECT "11/17/2021 14:10:24"        , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False" UNION
   SELECT "11/17/2021 14:10:25"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True"  UNION
   SELECT "11/17/2021 14:10:30"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "False" UNION
   SELECT "11/17/2021 14:10:31"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 14:10:32"        , "False", "False", "True" , "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "True" , "False", "False" UNION
   SELECT "11/17/2021 14:10:32"        , "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 14:10:34"        , "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "True" , "False", "True"  UNION
   SELECT "11/17/2021 14:10:47"        , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 14:10:47"        , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True"  UNION
   SELECT "11/17/2021 14:10:49"        , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "11/17/2021 14:10:58"        , "False", "False", "True" , "False", "True" , "False", "True" , "False", "True" , "False", "False", "True" , "False", "False", "True"  UNION
   SELECT "11/17/2021 14:11:07"        , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:11:08"        , "False", "True" , "True" , "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "11/17/2021 14:11:09"        , "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "11/17/2021 14:11:12"        , "True" , "False", "True" , "False", "False", "True" , "True" , "False", "False", "True" , "False", "False", "False", "True" , "False" UNION
   SELECT "11/17/2021 14:11:23"        , "False", "True" , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False";